name: say hello

on:
  push:
    branches: 
        -master


jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo message
        run: echo "hola cristopher"
      - name: Dime la fecha
        run: echo "ls -l"
        